### ISSUE TITLE
Automation triggered every time HA reboots

### ISSUE THREAD

**Issue by sfnetwork** [fireflyelectronix/wifidoorbell#3]
In Home Assistant, the MQTT trigger works when I ring the doorbell but the only pending issue I can't resolve it that the automation gets triggered every time I reboot HA or reload automations (or turn off and ON the automation.

I took the time to set it up following your doc:
First, I setup the doorbell:
- I configured the broker, port and “ha/doorbell/notify” for the topic.

- In HA, I setup this automation
```
- id: '1552933754824'
  alias: Notification - sonnette porte
  trigger:
  - platform: mqtt
    topic: ha/doorbell/notify
  condition: []
  action:
  - data:
      message: ding dong! Ça sonne à la porte!
      title: Home Assistant - sfHome
    service: notify.pushover_sylvain
  - data:
      delay: 00:00:05
      message: Ding dong! Ça sonne à la porte!!
      sonos_entity: media_player.bureau
      volume: '0.3'
    service: script.sonos_say
```

- Following the doc, I setup the battery sensor:

```
#Doobell MQTT battery  
  - platform: mqtt
    state_topic: "ha/doorbell/notify"
    value_template: '{{value_json.batt}}'
    unit_of_measurement: "Volts"
    name: "Batterie sonnette MQTT"  
```
This works fine.

- I tried setting up a binary sensor but it just switches on / off every time it’s triggered (or rebooted), not really helpful…

```
#Sonette de porte
  - platform: mqtt
    name: Sonnette porte
    state_topic: "ha/doorbell/notify"
    value_template: "{%if is_state(entity_id,\"on\")-%}OFF{%-else-%}ON{%-endif%}"
```

I don't know how to fix this since the doorbell just send this same MQTT topic every time...
***My knowloedge in MQTT is very new and limited BTW...
